### ISSUE TITLE
Cards for `/member` become massive on laptop screen

### ISSUE THREAD

**Issue by anuragrao04** [MUNSoc-PESUECC/MUNSocWebsite#23]
## About

The cards for members become really huge on a laptop screen. This is in the `/members` route. Please implement a limit to how big these cards can grow

## Bounty 25

**Comment by ani-netizen** [comment]
Hey @anuragrao04 

I can help you with this task, kindly assign it to me

**Comment by anuragrao04** [comment]
Hey! I really appreciate your interest but this issue is part of an internal hacktoberfest event. I'm sorry but I can't assign it to you

**Comment by alfadelta10010** [comment]
Anurag fixed it
